### ISSUE TITLE
questions about the reproducibility

### ISSUE THREAD

**Issue by FayeXXX** [BruceWen120/neurips-reproducibility-challenge-2019#3]
Thank you for your excellent work. After i read the origin paper and your paper,there are still have some questions:
1. How to choose the final results?
As the generated text are based on various weight(2.0-8.0) and runs for 5 iterations, there are 35 results.
2. The threshold t can not be found in the code.
The threshold is a important part in the FGIM algorithm.

Your reply will be greatly appreciated.

**Comment by BruceWen120** [comment]
Hi there, thanks for your interest in our report. Our report was meant to assess the reproducibility of the original paper, however, and so I think your questions would be better answered by authors of the original paper.

I'll close this for now, feel free to reopen in case you have more questions about our report.
